/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Poliko (https://sketchfab.com/Poliko)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lowpoly-bird-robin-e8083fd21a73438ca67b90307e6931e5
Title: Lowpoly bird (Robin)
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import PropTypes from 'prop-types'

export function Bird(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/bird.glb')
  const { actions } = useAnimations(animations, group)
  
  // Play animation when the bird is active
  React.useEffect(() => {
    // Play animation when the component is active
    if (props.isActive) {
      // Get the first animation or a specific animation if you know its name
      const animationName = Object.keys(actions)[0]
      if (actions[animationName]) {
        actions[animationName].reset().fadeIn(0.5).play()
      }
    } else {
      // Stop all animations when not active
      Object.values(actions).forEach(action => {
        if (action && action.isRunning && action.isRunning()) {
          action.fadeOut(0.5)
        }
      })
    }
  }, [props.isActive, actions])
  
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={1.182}>
          <group name="Poliko_Robin_sketchfabfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Pajaro_Robin">
                  <group name="polySurface2">
                    <group name="transform3" />
                  </group>
                  <group name="polySurface3">
                    <group name="transform9" />
                  </group>
                  <group name="polySurface4">
                    <group name="transform8" />
                  </group>
                  <group name="polySurface5">
                    <group name="transform10" />
                  </group>
                  <group name="polySurface6">
                    <group name="transform11" />
                  </group>
                  <group name="polySurface7">
                    <group name="transform7" />
                  </group>
                  <group name="polySurface8">
                    <group name="transform5" />
                  </group>
                  <group name="polySurface9">
                    <group name="transform6" />
                  </group>
                  <group name="polySurface10">
                    <group name="transform4" />
                  </group>
                  <group name="polySurface11">
                    <group name="transform2" />
                  </group>
                  <group name="polySurface12">
                    <group name="transform13" />
                  </group>
                  <group name="polySurface14">
                    <group name="transform12" />
                  </group>
                  <group name="transform1" />
                </group>
                <group
                  name="Camera"
                  position={[679.481, 618.832, 663.246]}
                  rotation={[-Math.PI, 0.756, 2.68]}
                  scale={100}>
                  <group name="Object_31" />
                </group>
                <group name="Robin_pos">
                  <group name="Object_33">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh
                      name="Object_58"
                      geometry={nodes.Object_58.geometry}
                      material={materials.Robin_Material}
                      skeleton={nodes.Object_58.skeleton}
                    />
                    <group name="Object_57" />
                  </group>
                </group>
                <group name="polySurface9_1">
                  <group name="transform15" />
                </group>
                <group name="polySurface6_1">
                  <group name="transform16" />
                </group>
                <group name="polySurface12_1">
                  <group name="transform14" />
                </group>
                <group
                  name="right1"
                  position={[1000.1, 6.923, 5.751]}
                  rotation={[-Math.PI, 0, -Math.PI]}>
                  <group name="Object_66" />
                </group>
                <group name="polySurface17" />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

Bird.propTypes = {
  isActive: PropTypes.bool
}

useGLTF.preload('/models/bird.glb')
