// filepath: d:\dev\NeuroXones\src\components\models\Player.jsx
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Player(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/player.glb");
  const { actions } = useAnimations(animations, group);
  
  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={nodes.Scene || scene} />
    </group>
  );
}

useGLTF.preload("/models/player.glb");
