/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import PropTypes from 'prop-types'

export function Player(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/player.glb')
  const { actions } = useAnimations(animations, group)
  
  // Play animation when the player is active
  useEffect(() => {
    // Play animation when the component is active
    if (props.isActive) {
      // Get the first animation or a specific animation if you know its name
      const animationName = Object.keys(actions)[0]
      if (actions[animationName]) {
        actions[animationName].reset().fadeIn(0.5).play()
      }
    } else {
      // Stop all animations when not active
      Object.values(actions).forEach(action => {
        if (action && action.isRunning && action.isRunning()) {
          action.fadeOut(0.5)
        }
      })
    }
  }, [props.isActive, actions])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="e405430fbdcc43f79db4240fa1a75914fbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="songyMaster_CTRL" />
                <group name="songyradio">
                  <group name="songyAntenna_GRP">
                    <group name="songyAntennabase_GEO" position={[11.681, 11.624, -3.969]}>
                      <group name="songyAntenna1_GEO" position={[0.175, 0.384, 0]}>
                        <mesh
                          name="songyAntenna1_GEO_songy_material_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.songyAntenna1_GEO_songy_material_0.geometry}
                          material={materials.songy_material}
                        />
                        <group name="songyAntenna2_GEO" position={[-7.523, 0, 0]}>
                          <mesh
                            name="songyAntenna2_GEO_songy_material_0"
                            castShadow
                            receiveShadow
                            geometry={nodes.songyAntenna2_GEO_songy_material_0.geometry}
                            material={materials.songy_material}
                          />
                          <group name="songyAntenna3_GEO" position={[-4.011, 0, 0]}>
                            <mesh
                              name="songyAntenna3_GEO_songy_material_0"
                              castShadow
                              receiveShadow
                              geometry={nodes.songyAntenna3_GEO_songy_material_0.geometry}
                              material={materials.songy_material}
                            />
                          </group>
                        </group>
                      </group>
                      <mesh
                        name="songyAntennabase_GEO_songy_material_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.songyAntennabase_GEO_songy_material_0.geometry}
                        material={materials.songy_material}
                      />
                    </group>
                  </group>
                  <group name="songyButtons_GRP">
                    <group name="songyFFbutton_GEO">
                      <mesh
                        name="songyFFbutton_GEO_songy_material_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.songyFFbutton_GEO_songy_material_0.geometry}
                        material={materials.songy_material}
                      />
                    </group>
                    <group name="songyPausebutton_GEO">
                      <mesh
                        name="songyPausebutton_GEO_songy_material_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.songyPausebutton_GEO_songy_material_0.geometry}
                        material={materials.songy_material}
                      />
                    </group>
                    <group name="songyPlaybutton_GEO">
                      <mesh
                        name="songyPlaybutton_GEO_songy_material_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.songyPlaybutton_GEO_songy_material_0.geometry}
                        material={materials.songy_material}
                      />
                    </group>
                    <group name="songyRecbutton_GEO">
                      <mesh
                        name="songyRecbutton_GEO_songy_material_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.songyRecbutton_GEO_songy_material_0.geometry}
                        material={materials.songy_material}
                      />
                    </group>
                    <group name="songyRWbutton_GEO">
                      <mesh
                        name="songyRWbutton_GEO_songy_material_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.songyRWbutton_GEO_songy_material_0.geometry}
                        material={materials.songy_material}
                      />
                    </group>
                    <group name="songyStopbutton_GEO">
                      <mesh
                        name="songyStopbutton_GEO_songy_material_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.songyStopbutton_GEO_songy_material_0.geometry}
                        material={materials.songy_material}
                      />
                    </group>
                  </group>
                  <group name="songyCogL_GEO" position={[-6.266, 5.19, 4.87]}>
                    <mesh
                      name="songyCogL_GEO_songy_material_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.songyCogL_GEO_songy_material_0.geometry}
                      material={materials.songy_material}
                    />
                  </group>
                  <group name="songyCogR_GEO" position={[-2.013, 5.19, 4.87]}>
                    <mesh
                      name="songyCogR_GEO_songy_material_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.songyCogR_GEO_songy_material_0.geometry}
                      material={materials.songy_material}
                    />
                  </group>
                  <group name="songyDialindicator_GEO" position={[-9.116, 12.276, 4.864]}>
                    <mesh
                      name="songyDialindicator_GEO_songy_material_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.songyDialindicator_GEO_songy_material_0.geometry}
                      material={materials.songy_material}
                    />
                  </group>
                  <group
                    name="songyDoorold_GRP"
                    position={[-9.863, -0.255, 6.05]}
                    rotation={[0.002, 0, 0]}>
                    <group name="songyDoor_GEO" position={[5.727, 2.036, 0.551]}>
                      <mesh
                        name="songyDoor_GEO_songy_material_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.songyDoor_GEO_songy_material_0.geometry}
                        material={materials.songy_material}
                      />
                      <group
                        name="songyInteriorCassette_GRP"
                        position={[8.274, 3.632, -12.075]}
                        rotation={[Math.PI, 0, Math.PI]}>
                        <group
                          name="cassetteInterior_GRP"
                          position={[8.281, 0.007, -10.856]}
                          rotation={[-Math.PI, 0, 0]}>
                          <group name="cassetteInterior_GEO" position={[0, 2.926, -0.388]}>
                            <mesh
                              name="cassetteInterior_GEO_cassette_material_06_0"
                              castShadow
                              receiveShadow
                              geometry={nodes.cassetteInterior_GEO_cassette_material_06_0.geometry}
                              material={materials.cassette_material_06}
                            />
                          </group>
                          <group name="cassetteInteriorCog1_GEO" position={[-2.128, 0.228, 0]}>
                            <mesh
                              name="cassetteInteriorCog1_GEO_cassette_material_06_0"
                              castShadow
                              receiveShadow
                              geometry={
                                nodes.cassetteInteriorCog1_GEO_cassette_material_06_0.geometry
                              }
                              material={materials.cassette_material_06}
                            />
                          </group>
                          <group name="cassetteInteriorCog2_GEO" position={[2.128, 0.228, 0]}>
                            <mesh
                              name="cassetteInteriorCog2_GEO_cassette_material_06_0"
                              castShadow
                              receiveShadow
                              geometry={
                                nodes.cassetteInteriorCog2_GEO_cassette_material_06_0.geometry
                              }
                              material={materials.cassette_material_06}
                            />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                  <group name="songyHandle" position={[0.114, 10.251, 1.472]}>
                    <mesh
                      name="songyHandle_songy_material_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.songyHandle_songy_material_0.geometry}
                      material={materials.songy_material}
                    />
                  </group>
                  <group
                    name="songyModeswitch_GEO"
                    position={[3.59, 12.991, 1.56]}
                    rotation={[0.419, 0, 0]}>
                    <mesh
                      name="songyModeswitch_GEO_songy_material_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.songyModeswitch_GEO_songy_material_0.geometry}
                      material={materials.songy_material}
                    />
                  </group>
                  <group name="songyRadiobody_GEO1">
                    <mesh
                      name="songyRadiobody_GEO1_songy_material_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.songyRadiobody_GEO1_songy_material_0.geometry}
                      material={nodes.songyRadiobody_GEO1_songy_material_0.material}
                    />
                  </group>
                  <group
                    name="songyRadioswitch_GEO"
                    position={[5.205, 12.991, 1.56]}
                    rotation={[-0.404, 0, 0]}>
                    <mesh
                      name="songyRadioswitch_GEO_songy_material_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.songyRadioswitch_GEO_songy_material_0.geometry}
                      material={materials.songy_material}
                    />
                  </group>
                  <group name="songyTuner_GEO" position={[12.142, 11.679, 2.18]}>
                    <mesh
                      name="songyTuner_GEO_songy_material_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.songyTuner_GEO_songy_material_0.geometry}
                      material={materials.songy_material}
                    />
                  </group>
                  <group
                    name="songyVolume_GEO"
                    position={[8.458, 13.697, 1.675]}
                    rotation={[-Math.PI, 0.723, -Math.PI]}>
                    <mesh
                      name="songyVolume_GEO_songy_material_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.songyVolume_GEO_songy_material_0.geometry}
                      material={materials.songy_material}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

Player.propTypes = {
  isActive: PropTypes.bool
}

useGLTF.preload('/models/player.glb')
