/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Brain(props) {
  const { nodes, materials } = useGLTF('/models/brain.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stylized_Human_Brain.geometry}
        material={materials.HumanBrain_Texture}
        position={[0, -0.01, 0]} // Centered position
        scale={1.8}
      />
    </group>
  )
}

useGLTF.preload('/models/brain.glb')