/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Neuroxone(props) {
  const { nodes, materials } = useGLTF('/models/neuroxone3.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.054, 0.124, 0.007]} rotation={[1.559, -0.837, 1.556]} scale={0.114}>
        <group position={[-0.434, 0.094, -0.019]} rotation={[-0.269, 0.256, 3]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wifi_symbol003_1.geometry}
            material={materials.color}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wifi_symbol003_2.geometry}
            material={materials['Material.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wifi_symbol003_3.geometry}
            material={materials['couro.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wifi_symbol003_4.geometry}
            material={materials['METAL.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wifi_symbol003_5.geometry}
            material={materials['black plastic.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wifi_symbol003_6.geometry}
            material={materials['Material.013']}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/neuroxone3.glb')
